### ISSUE TITLE
POE?

### ISSUE THREAD

**Issue by nardev** [5N44P/omega-dock-new#9]
Is there any space for adding voltage regulator of buck converter and  having POE  through lan?

(p.s. sorry i didn't look in details, maybe you already have that there but i can't find it...)

**Comment by nardev** [comment]
Ou i see lm1117 there.. is it for POE??? Buck  converter would be better since 1117 is horrible with voltage above 5V and in long ethernet lines you certainly can't be sure that you will be able to provide ~5V.. most likely you will get something like 10-30V...

**Comment by valerionew** [comment]
POE would be very interesting for this project. Unfortunately i don't have any experience in implementig it. For what I can understand, poe needs a transformer and some connections between the RJ45 connector and the magnetics. While maybe I can find some room for the transformer, in this project the magnetics are integrated in the connector, and I don't think that I will be able to use discrete magnetics for space reasons.

**Comment by valerionew** [comment]
By the way the 1117 is there to regulate the 5V provided by the microusb

**Comment by nardev** [comment]
You can leave LM1117 and just add "buck converter", there are plenty chips doing that.. would not take much more space... i prefer MCP16311 based one.. you can get 3.3V from  there too but better leave LM1117 and get voltage down to 5V first... btw there are other converters which can provide up to 3A.. 

would be great to see that...

**Comment by nardev** [comment]
p.s. You can also add "optional" solder on place for buck converter, a lot of ppl do that

for example
http://www.ebay.com/itm/5pcs-DC-DC-Buck-Step-Down-Voltage-Regulator-Mini-Module-3-3V-5V-6V-9V-12V-3A-/192035375555?hash=item2cb63349c3:g:u14AAOSwHMJYNZ64

Those are so popular, you can even buy it from digikey as that one...

so, just extending wires.... if there is no power from USB, get it from through Ethernet  cable :D

**Comment by valerionew** [comment]
But the big problem here is how to get the power from the ethernet, not how to step it down. As you said, there are plenty step down solutions. The troubles are how to get the power from the connector to the step down and how to isolate it

**Comment by nardev** [comment]
Aha, that is your concern... Well other did that..somehow, i  didn't try but it  must be  doable... perhaps those tiny lines would work fine.. maybe 4 layer PCB?

After that is out of your domain in this case...

p.s. For example, i would use this
http://www.ebay.com/itm/PoE-Adapter-RJ45-Injector-Power-over-Ethernet-Passive-Splitter-5V-12V-24V-48V-/152658307291?epid=1147936833&hash=item238b24e8db:g:XM8AAOSwpIxZdjHX

**Comment by valerionew** [comment]
The big issue is not tracks, they can be tiny and run under the components. My concern is about room for components. They won't fit in such a tiny space. The alternative could be using smd connectors to gain some space on the back side. But its still a tiny board. 

Regarding the adapter you linked: why not just injecting 5v? I mean.. The omega current requirement is tiny, the cable power lossew would be small.

**Comment by nardev** [comment]
Hm,, POE is very handy sometimes.. depends on cable, i really don't know if 5V can be carried more than 10 meters.. and.. it's comfortable if you have step down converter which can accept everything from 45 to 6V ...thank you don't think much about that... you can have only one cable and device far away...

any way,, there is no enough space on your current board but certainly there is potential for that...

**Comment by valerionew** [comment]
https://github.com/zeroping/OmegaPoE
Looks like @zeroping did an amazing job bringing the poe to the omega within a tiny board, check out his work 😄

**Comment by zeroping** [comment]
Hey, it hasn't worked yet. We'll see if the whole thing catches on fire when I plug it in. I'll have my first development boards in about a month, so follow [here](https://community.onion.io/topic/2968/omega-poe-dock/) for updates.

And yes, regarding safety and distance, that's why I'm doing 802.3af - they put a lot of work into that standard to make it compatible and safe.
